==20825== Memcheck, a memory error detector
==20825== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==20825== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==20825== Command: ./fdf test_maps/42.fdf
==20825== Parent PID: 8427
==20825== 
==20825== Invalid write of size 4
==20825==    at 0x402C1D: parsing (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402495: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==  Address 0x20 is not stack'd, malloc'd or (recently) free'd
==20825== 
==20825== 
==20825== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==20825==  Access not within mapped region at address 0x20
==20825==    at 0x402C1D: parsing (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402495: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==  If you believe this happened as a result of a stack
==20825==  overflow in your program's main thread (unlikely but
==20825==  possible), you can try to increase the size of the
==20825==  main thread stack using the --main-stacksize= flag.
==20825==  The main thread stack size used in this run was 8388608.
==20825== 
==20825== HEAP SUMMARY:
==20825==     in use at exit: 1,368 bytes in 29 blocks
==20825==   total heap usage: 57 allocs, 28 frees, 7,180 bytes allocated
==20825== 
==20825== 40 bytes in 1 blocks are still reachable in loss record 1 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x489AE49: XInitThreads (locking.c:606)
==20825==    by 0x4004CDD: call_init (dl-init.c:70)
==20825==    by 0x4004CDD: call_init (dl-init.c:26)
==20825==    by 0x4004DCB: _dl_init (dl-init.c:117)
==20825==    by 0x401B8DF: ??? (in /usr/lib64/ld-linux-x86-64.so.2)
==20825==    by 0x1: ???
==20825==    by 0x1FFEFFFE3E: ???
==20825==    by 0x1FFEFFFE44: ???
==20825== 
==20825== 40 bytes in 1 blocks are still reachable in loss record 2 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x489AE66: XInitThreads (locking.c:608)
==20825==    by 0x4004CDD: call_init (dl-init.c:70)
==20825==    by 0x4004CDD: call_init (dl-init.c:26)
==20825==    by 0x4004DCB: _dl_init (dl-init.c:117)
==20825==    by 0x401B8DF: ??? (in /usr/lib64/ld-linux-x86-64.so.2)
==20825==    by 0x1: ???
==20825==    by 0x1FFEFFFE3E: ???
==20825==    by 0x1FFEFFFE44: ???
==20825== 
==20825== 40 bytes in 1 blocks are still reachable in loss record 3 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x489AE83: XInitThreads (locking.c:613)
==20825==    by 0x4004CDD: call_init (dl-init.c:70)
==20825==    by 0x4004CDD: call_init (dl-init.c:26)
==20825==    by 0x4004DCB: _dl_init (dl-init.c:117)
==20825==    by 0x401B8DF: ??? (in /usr/lib64/ld-linux-x86-64.so.2)
==20825==    by 0x1: ???
==20825==    by 0x1FFEFFFE3E: ???
==20825==    by 0x1FFEFFFE44: ???
==20825== 
==20825== 40 bytes in 1 blocks are still reachable in loss record 4 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x402435: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 40 bytes in 1 blocks are still reachable in loss record 5 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x40244F: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 56 bytes in 1 blocks are still reachable in loss record 6 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x402469: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 56 bytes in 1 blocks are still reachable in loss record 7 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x4059E3: get_correct_line (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x405BE6: get_next_line (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402B87: parsing (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402495: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 176 bytes in 11 blocks are still reachable in loss record 8 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x40587B: ft_lstnew (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402BD5: parsing (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402495: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 320 bytes in 1 blocks are still reachable in loss record 9 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x40241F: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== 560 bytes in 10 blocks are still reachable in loss record 10 of 10
==20825==    at 0x4E050C5: malloc (vg_replace_malloc.c:393)
==20825==    by 0x4059E3: get_correct_line (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x405BE6: get_next_line (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402BC8: parsing (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825==    by 0x402495: main (in /home/aurel/Documents/CLionProjects/FdF/fdf)
==20825== 
==20825== LEAK SUMMARY:
==20825==    definitely lost: 0 bytes in 0 blocks
==20825==    indirectly lost: 0 bytes in 0 blocks
==20825==      possibly lost: 0 bytes in 0 blocks
==20825==    still reachable: 1,368 bytes in 29 blocks
==20825==         suppressed: 0 bytes in 0 blocks
==20825== 
==20825== For lists of detected and suppressed errors, rerun with: -s
==20825== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
